### ISSUE TITLE
Migrate from swapi

### ISSUE THREAD

**Issue by filoxo** [react-microfrontends/api#4]
Swapi is no longer maintained and the heroku instance hosting it has stopped working. See https://github.com/phalt/swapi/issues/147

We should migrate from this API and update the project. We could either:

- spin up our own instance of swapi (now.sh or similar?)
- migrate to another open API like pokeapi.co or official GitHub REST

**Comment by internettrans** [comment]
@TheMcMurder thoughts on this?

**Comment by frehner** [comment]
another alternative https://jsonplaceholder.typicode.com

**Comment by TheMcMurder** [comment]
I'm leaning towards fake API calls to a JSON file that has the swapi data in them.

I don't want to have another migration when pokeapi.co goes down and I'm not sure I want to maintain the swapi code (because I'm unfamiliar with it).

Although the biggest problem with that approach is that it doesn't illustrate it as well as a real API with actual endpoints.
